import test from "node:test";
import assert from "node:assert/strict";
import { once } from "node:events";
import type { AddressInfo } from "node:net";
import { createApiServer } from "../../api/http.ts";
import { createStore } from "../../api/store.ts";
import { buildPlayerReceipt, validateMatchReceipt } from "../../../packages/elo-engine/src/receipts.ts";
import { proxyApi } from "../lib/proxy.ts";

test("two public browser sessions import, consent, match, recover and download real receipts", async (t) => {
  const store = createStore({ databasePath: ":memory:", now: () => new Date("2026-09-14T16:00:00Z") });
  const serviceKey = "integration-service-key-" + "s".repeat(32);
  const server = createApiServer({ store, serviceKey });
  server.listen(0, "127.0.0.1"); await once(server, "listening");
  t.after(async () => { server.closeAllConnections(); await new Promise<void>(resolve => server.close(() => resolve())); store.close(); });
  const apiUrl = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  const call = async (path: string, method = "GET", data?: unknown, cookie?: string) => {
    const headers: Record<string, string> = { origin: "https://league.test", "content-type": "application/json" };
    if (cookie) headers.cookie = cookie;
    const req = new Request(`https://league.test/api/${path}`, { method, headers, ...(data !== undefined ? { body: JSON.stringify(data) } : {}) });
    const response = await proxyApi(req, path.split("?")[0]!.split("/").map(decodeURIComponent), { apiUrl, serviceKey });
    return response;
  };
  const a = await call("players", "POST", { username: "alice", token: "a".repeat(64) }), b = await call("players", "POST", { username: "bob", token: "b".repeat(64) });
  assert.equal(a.status, 201); assert.equal(b.status, 201);
  const cookieA = a.headers.get("set-cookie")!.split(";")[0]!, cookieB = b.headers.get("set-cookie")!.split(";")[0]!;
  const playerA = await a.json(), playerB = await b.json();
  assert.notEqual(playerA.player.id, playerB.player.id);
  const form = (score: number) => buildPlayerReceipt({ player_id: "p_" + "1".repeat(32), competition_id: "c_" + "2".repeat(32), week_id: "2026-W37", form_score: score, coverage_ppm: 850_000, certainty_ppm: 800_000 });
  assert.equal((await call("assessment", "POST", { weekId: "2026-W37", formScore: 850, coveragePpm: 850000, certaintyPpm: 800000 }, cookieA)).status, 200);
  assert.equal((await call("form", "POST", { receipt: form(750) }, cookieB)).status, 200);
  assert.equal((await (await call("queue", "POST", { mode: "scalar" }, cookieA)).json()).status, "queued");
  const paired = await call("queue", "POST", { mode: "scalar" }, cookieB);
  assert.equal(paired.status, 200);
  const { match } = await paired.json();
  validateMatchReceipt(match);
  assert.equal(match.rating_effect, "rated");
  assert.equal(match.players.a.applied_delta_milli + match.players.b.applied_delta_milli, 0);
  const replay = await (await call("queue", "POST", { mode: "scalar" }, cookieA)).json();
  assert.equal(replay.match.fingerprint, match.fingerprint);
  const state = await (await call("me", "GET", undefined, cookieA)).json();
  assert.equal(state.player.username, "alice");
  assert.equal(state.usernames[playerB.player.id], "bob");
  assert.equal((await (await call("users/alice")).json()).player.id, playerA.player.id);
  assert.equal(state.player.receipt.elo.scalar.rated_matches, 1);
  assert.equal(state.player.receipt.elo.binary.rated_matches, 0);
  const archive = await call(`receipts/${encodeURIComponent(match.fingerprint)}`);
  assert.equal((await archive.json()).fingerprint, match.fingerprint);
  const card = await call(`matches/${match.match_id}/card.svg`);
  assert.equal(card.status, 200); assert.match(card.headers.get("content-type")!, /svg/);
  assert.match(await card.text(), /<svg/);
  const restored = await call("session", "POST", { token: playerA.recoveryKey });
  assert.equal(restored.status, 200); assert.ok(restored.headers.get("set-cookie"));
  assert.equal((await restored.json()).player.id, playerA.player.id);
  assert.equal((await call("form", "POST", { receipt: form(999) }, cookieA)).status, 409);
  const replacementToken = "c".repeat(64);
  const rotated = await call("session/rotate", "POST", { replacementToken }, cookieA);
  assert.equal(rotated.status, 200);
  assert.equal((await rotated.json()).recoveryKey, replacementToken);
  const revoked = await call("me", "GET", undefined, cookieA);
  assert.equal(revoked.status, 401);
  assert.match(revoked.headers.get("set-cookie")!, /Max-Age=0/);
  const recoveredRotation = await call("session", "POST", { token: replacementToken });
  assert.equal((await recoveredRotation.json()).player.receipt.elo.scalar.rated_matches, 1);
});
